### ISSUE TITLE
Links auf einzelne Bücher aus overview-Page fehlen

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42.de-site#13]
* [arc42 in Aktion]()
* [arc42 by Example, Vol. 1](), arc42 anhand von sechs praktischen Beispielen erklärt
* [arc42 by Example, Vol. 2](), Beispiele aus den Bereichen Echtzeit- und Embedded
Da müssen Links auf die Seiten-Anker rein.

**Comment by Per-Starke** [comment]
@gernotstarke this looks just fine, links are working, can this be closed?
