### ISSUE TITLE
Politische Statements und arc42Website

### ISSUE THREAD

**Issue by fflorey** [arc42/arc42.de-site#51]
Ich bin seit längerem einmal wieder auf der Seite vorbeigekommen (arc42.de) und bin etwas irritiert von der wehenden Ukrainischen Flagge über den zentralen Aussagen zu arc42. 
"Entwerfen, kommunizieren und dokumentieren. Bewährt, praktisch und pragmatisch. Frei verfügbar, Open-Source und schmerzfrei."
Der Link auf der Seite führt auch auf die (hoch)politische Seite "https://u24.gov.ua/", auf der unter Hilfe zur Ukraine sehr prominent direkte Hilfszahlungen für das Militär gewünscht werden. 
Unabhängig von meiner persönlichen Einstellung zu diesem Thema fände ich es sinnvoll von einer derart prominenten Vermischung von inhaltlichen Aussagen zu arc42 politischen Statements abzusehen und mindestens eine deutliche optische Trennung herbeizuführen.

BTW: Danke für die Arbeit an arc42!

**Comment by gernotstarke** [comment]
@fflorey - danke für Deine Stellungnahme.

Wir sehen diese deutliche Markierung als eines der wenigen Mittel, die wir (neben unseren eigenen Spenden) haben,
um auf die fatale Situation in der Ukraine aufmerksam zu machen. Zugegeben - vermutlich rettet unsere deutlich sichtbare Fahne keine Menschenleben - aber wir möchten dieses deutliche politische Signal setzen.

Da wir völlig auf Cookies verzichten, können wir nicht so einfach einen Mechanismus implementieren, mit dem User wie Du die Flagge und den ua-Link ausschalten können. Wenn Du eine Idee dafür hast, gerne her damit.

Und bezüglich arc42 generell: sehr gerne - seit 2004 mit großer Begeisterung.

@Hruschka - Deine Meinung?

**Comment by Hruschka** [comment]
@fflorey - ja, ich sehe es auch kritisch, auf einer Techie-Seite über Politik reden zu. müssen.

ich bin nach dem zweiten Weltkrieg geboren und hatte das Glück (im Gegensatz zu meinen Eltern und Großeltern), mein ganzes bisheriges Leben in einer friedlichen Gesellschaft zu leben.

Um so mehr bedrückt es, diesen sinnlosen Angriffskrieg miterleben zu müssen.
Wie Gernot schon gesagt hat, sind unsere Möglichkeiten zur Hilfe sehr begrenzt. Aber gerade wegen unserer informellen beruflichen Bekanntschafen mit IT'ler aus der Ukraine bin ich gerne bereit, wenigstens diese kleine moralische Unterstützung zu bieten.

**Comment by gernotstarke** [comment]
Ich lasse den Issue trotzdem offen - damit andere unsere Meinungen sehen können!!

**Comment by gernotstarke** [comment]
wir haben mittlerweile einen anderen Link zur Unterstützung und haben optisch unsere Unterstützung etwas dezenter angelegt.
daher schliesse ich das Issue...
